#!/usr/bin/env python
#-*- coding: utf-8 -*-

try:
    import readline
    import rlcompleter
    import os
    import atexit
except ImportError, e:
    print e
else:
    class TabCompleter(rlcompleter.Completer):
        """Completer that support tab indenting"""
        def complete(self, text, state):
            if not text:
                return ('\t', None)[state]
            else:
                return rlcompleter.Completer.complete(self, text, state)
    readline.set_completer(TabCompleter().complete)
    if 'libedit' in readline.__doc__:
        """Complete filename (tab key)
        http://minix1.woodhull.com/manpages/man3/editline.3.html"""
        readline.parse_and_bind('bind ^I rl_complete')
    else:
        readline.parse_and_bind('tab: complete')
    histfile = os.path.expanduser('~/.pyhistory')
    def savehist(histfile=histfile):
        import readline
        readline.write_history_file(histfile)
    atexit.register(savehist)
    if os.path.exists(histfile):
        readline.read_history_file(histfile)
    del readline, os, atexit, histfile, savehist
