#!/bin/bash

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# play safe
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias ll='ls -aFhl'

# typing errors...
alias ..='cd ..'
alias ...='cd ../..'

alias df='df -h'
alias du='du -h'
alias gdb='gdb --quiet'

alias date='date +"%Z %F %T"'
