#!/usr/bin/env python3

import os
import sys


def proc():
    if is_branch_checkout == "0":
        print("post-checkout: This is a file checkout. Nothing to do.")
        return
    print("post-checkout: deleting all '.pyc' files in working directory ...")
    for root, dirs, files in os.walk('.'):
        for filename in files:
            ext = os.path.splitext(filename)[1]
            if ext == '.pyc':
                os.unlink(os.path.join(root, filename))


if __name__ == '__main__':
    # collect the parameters
    previous_head = sys.argv[1]
    new_head = sys.argv[2]
    is_branch_checkout = sys.argv[3]
    proc()
