#!/usr/bin/env python3


import sys
import subprocess as subp


def proc():
    # check if this is the initial commit
    cmd = 'git rev-parse --verify HEAD'
    retcode = subp.call(cmd.split(), stdin=subp.DEVNULL, stdout=subp.DEVNULL, stderr=subp.DEVNULL)
    retcode = 0
    against = 'HEAD'
    if retcode != 0:
        # "pre-commit: About to create the first commit..."
        against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'

    # use git diff-index to check for whitespace errors
    cmd = f'git diff-index --check --cached {against}'
    retcode = subp.call(cmd.split(), stdin=subp.DEVNULL, stdout=subp.DEVNULL, stderr=subp.DEVNULL)
    if retcode != 0:
        raise ValueError('whitespace error(s) found')


if __name__ == '__main__':
    try:
        proc()
    except Exception as e:
        print(f'[ERROR] pre-commit: {e}', file=sys.stderr)
        sys.exit(1)
