#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

# get computer name to append in Chime message
username="$USER"

# a branch name where you want to prevent git push. In this case, it's "master"
if [ "$branch" = "master" ]; then
  echo "You can't commit directly to '"${branch}"' branch" # webstorm or intellij will show this as popup
  curl -X POST "<Chime-Webhook-URL>" -H "Content-Type:application/json" --data '{"Content": "@All 🚧  '@"${username}"' trying to push code to '"${branch}"'. \n Please note that commit is not blocked but it is discouraged to push code directly to '"${branch}"'."}'
  exit 1 # if you remove this line then it won't block push but send message to group and on command line
fi
