#!/usr/bin/env python3
#
# This hook is invoked by git-commit(1) and git-merge(1),
# and can be bypassed with the --no-verify option.
# It takes a single parameter, the name of the file that holds the proposed commit log message.
# Exiting with a non-zero status causes the command to abort.
#
# The hook is allowed to edit the message file in place,
# and can be used to normalize the message into some project standard format.
# It can also be used to refuse the commit after inspecting the message file.

import re
import sys
from common import CommitCategory, msgdump


def proc(f):
    subject = f.readline().rstrip()
    subject_pattern = r'^\[(?P<category>[a-z]{3,10})\] (?P<summary>.{20,50})'
    r = re.fullmatch(subject_pattern, subject)
    if not r:
        raise ValueError(f'subject ({subject}) does match pattern: [{subject_pattern}]')
    category, summary = r.groups()
    category = CommitCategory(category)
    if not 20 <= len(summary) <= 50:
        raise ValueError(f'the length of summary is expected to be in the range [20, 50], {len(summary)} got')
    if subject.endswith('.'):
        raise ValueError('do not end the subject line with any period')
    for line in f:
        if line.startswith('#'):
            continue
        line = line.rstrip()
        if line:
            raise ValueError(f'a blank line is expected to separate the subject from body, but found line: [{line}]')
        else:
            break
    line_count = 2
    max_line_length = 72
    max_line_count = 30
    for line in f:
        if line.startswith('#'):
            continue
        line_count += 1
        if line_count > max_line_count:
            raise ValueError(f'body line count exceeds {max_line_count}, use a wiki instead')
        if len(line) > max_line_length:
            raise ValueError(f'body should wrapped at {max_line_length} characters, {len(line)} got')


if __name__ == '__main__':
    commit_msg_fpath = sys.argv[1]
    try:
        with open(commit_msg_fpath) as f:
            proc(f)
    except Exception as e:
        msgdump('error', f'{e}')
        sys.exit(1)
