#!/usr/bin/env python3

import os
import sys


def proc():
    print("post-checkout: deleting all '.pyc' files in working directory ...")
    for root, dirs, files in os.walk('.'):
        for filename in files:
            ext = os.path.splitext(filename)[1]
            if ext == '.pyc':
                os.unlink(os.path.join(root, filename))


if __name__ == '__main__':
    previous_head = sys.argv[1]
    new_head = sys.argv[2]
    is_branch_checkout = sys.argv[3]
    if is_branch_checkout == '0':
        # this is a file checkout. Nothing to do
        sys.exit(0)
    try:
        proc()
    except Exception as e:
        print(f'[ERROR] post-checkout: {e}', file=sys.stderr)
