#!/usr/bin/env python3

import sys
from common import current_branch, msgdump


def proc():
    branch = current_branch()
    if branch == 'master':
        # rebase on master is dangerous. don't do it.
        raise ValueError("rebasing on master is prohibited")


if __name__ == '__main__':
    try:
        proc()
    except Exception as e:
        msgdump('error', f'{e}')
        sys.exit(1)
