#!/usr/bin/env python3

import sys
import common


def proc():
    branch = common.current_branch()
    if branch == 'master':
        # rebase on master is dangerous. don't do it.
        raise ValueError("rebasing on master is prohibited")


if __name__ == '__main__':
    try:
        proc()
    except Exception as e:
        print(f'[ERROR] pre-rebase: {e}', file=sys.stderr)
        sys.exit(1)
